prevent appending pr_id urls with base_api_url
jupyterlab/pull-requests pull request #61
Opened 2021-09-14 14:17 UTC by meihkv

Only url_path_join(self.base_api_url, url) if `pr_id = get_request_attr_value(self, “id”)` already contains a fully qualified url.
Example:
If pr_id already starts with `http`, then don’t prefix it with base_api_url.
This occurs within Enterprise Github where we need to specify a custom base api url such as `http://api.githubprod.com`

2021-09-14 14:31 UTC, fcollonval commented
Hey @meihkv thanks for reaching out. I'm not sure to understand your issue (and therefore this PR). If you are using a custom GitHub server, you need to set `PRConfig.api_base_url` to your server url - aka `http://api.githubprod.com` (see [README](https://github.com/jupyterlab/pull-requests#settings)).

2021-09-14 17:43 UTC, fcollonval commented
Thanks for the clarification.

Does that mean that `https://api.githubprod.prci.com/` is an alias for `https://githubprod.prci.com/api`?

2021-09-15 12:10 UTC, meihkgnuov commented
Sorry, I don't know what an alias means in this context, so I'm not sure how to answer that.  What can I do to check if it's an alias?

The extension makes the correct _call_provider every time with https://api.githubprod.prci.com/, but for pull requests, it doesn't need the base_api_url.  I don't know if that's specific to my organization or if that behavior applies to all custom Github Enterprise Apis.

2021-09-15 13:01 UTC, fcollonval requested changes
Don't worry that was more for my information.

Could you please make the change (see comment in the code)?

2021-09-15 13:49 UTC, meihkgnuov commented on jupyterlab_pullrequests/managers/manager.py
> +        if (not url.startswith(self.base_api_url)) and (not url.startswith("http")):
Absolutely.  Is this what you had in mind?
```
if (not url.startswith(self.base_api_url)) and (not re.search("^https", url)):
```

2021-09-15 14:49 UTC, fcollonval commented on jupyterlab_pullrequests/managers/manager.py
> +        if (not url.startswith(self.base_api_url)) and (not url.startswith("http")):
Yes, could you use `^https?:` (with the interrogation point and the column) to cover also the case of non secure URLs and to be sure this is not a path like `httppath-to-api/...` that need adding the base url

2021-09-16 12:54 UTC, meihkv commented on jupyterlab_pullrequests/managers/manager.py
> +        if (not url.startswith(self.base_api_url)) and (not url.startswith("http")):
Done! I’ve updated the branch. I’ve also imported re at the top.

2021-09-16 13:52 UTC, merged